apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  type: {{ .Values.service.type }}
