# Основные настройки приложения
app:
  name: my-app
  version: v1

# Настройки образа
image:
  repository: vadimzakharov9243/myapp
  tag: latest
  pullPolicy: Always

# Количество реплик
replicaCount: 1

# Настройки контейнера
container:
  stdin: true
  tty: true
  metricsPort: 8080

# Ресурсы
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

# Мониторинг
monitoring:
  prometheus:
    scrape: true
    port: "8080"
    path: "/metrics"

# Сервис
service:
  type: NodePort
  port: 80
  targetPort: metrics
